name: Deploy statics on public repo
on:
  push:
    branches: 
      - main
    paths:
      - 'src/content/**'
      - 'src/pages/**'

jobs:
  build:
    name: create-package
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        name: Use Node.js 21
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install Yarn
        run: npm install --global yarn

      - name: Install dependencies with Yarn
        run: yarn install
      
      - name: Build the project with Yarn
        run: yarn build
        env:
          CI: false

      - run: ls -R dist

      - name: Push built files to public repo
        run: |
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"
          git clone https://${{ secrets.API_TOKEN_GITHUB }}@github.com/${{ secrets.GIT_USER }}/${{ secrets.GIT_REPO }}.git deploy_repo
          rm -rf deploy_repo/*
          cp -R dist/* deploy_repo/
          cd deploy_repo
          git add .
          COMMIT_MESSAGE="Deploy new version - $(date -u +"%Y-%m-%d %H:%M:%S UTC")"
          git commit -m "$COMMIT_MESSAGE"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}